# Generated by Django 4.0 on 2021-12-25 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=200)),
                ('user_image', models.ImageField(upload_to='user_images/<django.db.models.fields.EmailField>/')),
                ('reg_date', models.DateTimeField(verbose_name='Дата регистрации')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=200)),
                ('quiz_image', models.ImageField(upload_to='user_images/<function Quiz.getEmail at 0x7fb4f998cf70>/<django.db.models.fields.CharField>/')),
                ('question_num', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.user')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('answer_num', models.IntegerField(default=0)),
                ('question_image', models.ImageField(upload_to='user_images/<function Question.getEmail at 0x7fb4f99a13a0>/<function Question.getQuizName at 0x7fb4f99a1430>/<django.db.models.fields.CharField>/')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=200)),
                ('points', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
        ),
    ]
