# Generated by Django 4.0 on 2021-12-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(upload_to='user_images/<function Question.getUsername at 0x7f984ef9b4c0>/<function Question.getQuizName at 0x7f984ef9b550>/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_image',
            field=models.ImageField(upload_to='user_images/<function Quiz.getUsername at 0x7f984ef9b0d0>/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(upload_to='user_images/<django.db.models.fields.CharField>/'),
        ),
    ]
