# Generated by Django 4.0 on 2021-12-26 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_question_question_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_num',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question_num',
        ),
    ]
