# Generated by Django 4.0 on 2022-01-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='play_date',
            field=models.DateTimeField(default=0, verbose_name='Publication date'),
            preserve_default=False,
        ),
    ]
