# Generated by Django 4.0 on 2022-01-19 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_play_play_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='play_date',
        ),
    ]
